### ISSUE TITLE
Give practical examples 

### ISSUE THREAD

**Issue by OrionRandD** [Zacalot/bible-mode#3]
Could you, please, give some practical examples on how to use your program?
Especially the Greek and Hebrew modes to study Bible words.
I have tried here, but nothing happens.

my config works and is:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; bible-mode

 (add-to-list 'load-path "~/_emacs.d_Orig/local-repo/bible-mode");;
 (require 'bible-mode);;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

When I hit "w", it opens a Bible with Strong Hebrew numbers. But, when I hit Enter on a number, Emacs just shows a clock that never stops...  :(

**Comment by Zacalot** [comment]
Hey, yeah I don't know why enabling word study would cause it to freeze, never experienced that. If you can view chapters without it, you should be able to view chapters with it since all it does is enable certain tags from the diatheke query to render. The example image in the repo shows what it should look like, so this sounds more like a bug than a user error. As for troubleshooting this, what translation module are you using? This was developed exclusively with the KJV module during testing, so it's possible other modules may have issues due to differences in their tags/formatting. Otherwise, it may be worthwhile to make sure your diatheke program is up to date. You also could try disabling all your emacs packages except bible-mode to make sure you don't have any other packages conflicting with this one.
Also I don't see anything wrong with your config as long as you have the package repo up to date, though I wouldn't know for certain since I don't install emacs packages in the same manner. Here's the config I use to download and load it:
```
(use-package bible-mode
  :straight (
             :host github
             :repo "Zacalot/bible-mode"))
```

**Comment by OrionRandD** [comment]
What is supposed to happen when you place the point on a Strong word number and hit Enter?
Could you make a small demo of you using bible-mode? If possible....

**Comment by OrionRandD** [comment]
> Hey, yeah I don't know why enabling word study would cause it to freeze, never experienced that. If you can view chapters without it, you should be able to view chapters with it since all it does is enable certain tags from the diatheke query to render. The example image in the repo shows what it should look like, so this sounds more like a bug than a user error. As for troubleshooting this, what translation module are you using? This was developed exclusively with the KJV module during testing, so it's possible other modules may have issues due to differences in their tags/formatting. Otherwise, it may be worthwhile to make sure your diatheke program is up to date. You also could try disabling all your emacs packages except bible-mode to make sure you don't have any other packages conflicting with this one. Also I don't see anything wrong with your config as long as you have the package repo up to date, though I wouldn't know for certain since I don't install emacs packages in the same manner. Here's the config I use to download and load it:
> 
> ```
> (use-package bible-mode
>   :straight (
>              :host github
>              :repo "Zacalot/bible-mode"))
> ```

I am also getting these warnings:

/scimax/user/local-repo/bible-mode/bible-mode.el: Warning: ‘return’ is an obsolete alias (as of 27.1); use ‘cl-return’ instead. [4 times]

I think that (return) in the code should be named (cl-return)
Thx

**Comment by Zacalot** [comment]
I pushed a change to replace those functions, and here's a gif of my using the strongs word lookup:

![Animation](https://github.com/Zacalot/bible-mode/assets/23412899/fb6d9903-a069-45aa-b826-e3dcf2cd684c)

So all it does is open a side pane for the word at the caret.

**Comment by OrionRandD** [comment]
> I pushed a change to replace those functions, and here's a gif of my using the strongs word lookup:
> 
> ![Animation](https://private-user-images.githubusercontent.com/23412899/285564753-fb6d9903-a069-45aa-b826-e3dcf2cd684c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ5NTYsIm5iZiI6MTcwMDkyNDY1NiwicGF0aCI6Ii8yMzQxMjg5OS8yODU1NjQ3NTMtZmI2ZDk5MDMtYTA2OS00NWFhLWI4MjYtZTNkY2YyY2Q2ODRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE1MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjVjYTFhMThjZDliOTEzN2QxMmE3MWEyYTU1Y2NjNGY4MmYzNDI2NzhhMmZhYmNiNzE1YTIzYTg3MmUzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3mzt4H3cLjtGZAfCc7QfUgzQ0vceJUKbUbRY9HQbn4) [ ![Animation](https://private-user-images.githubusercontent.com/23412899/285564753-fb6d9903-a069-45aa-b826-e3dcf2cd684c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ5NTYsIm5iZiI6MTcwMDkyNDY1NiwicGF0aCI6Ii8yMzQxMjg5OS8yODU1NjQ3NTMtZmI2ZDk5MDMtYTA2OS00NWFhLWI4MjYtZTNkY2YyY2Q2ODRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE1MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjVjYTFhMThjZDliOTEzN2QxMmE3MWEyYTU1Y2NjNGY4MmYzNDI2NzhhMmZhYmNiNzE1YTIzYTg3MmUzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3mzt4H3cLjtGZAfCc7QfUgzQ0vceJUKbUbRY9HQbn4) ](https://private-user-images.githubusercontent.com/23412899/285564753-fb6d9903-a069-45aa-b826-e3dcf2cd684c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ5NTYsIm5iZiI6MTcwMDkyNDY1NiwicGF0aCI6Ii8yMzQxMjg5OS8yODU1NjQ3NTMtZmI2ZDk5MDMtYTA2OS00NWFhLWI4MjYtZTNkY2YyY2Q2ODRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE1MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjVjYTFhMThjZDliOTEzN2QxMmE3MWEyYTU1Y2NjNGY4MmYzNDI2NzhhMmZhYmNiNzE1YTIzYTg3MmUzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3mzt4H3cLjtGZAfCc7QfUgzQ0vceJUKbUbRY9HQbn4) [ ](https://private-user-images.githubusercontent.com/23412899/285564753-fb6d9903-a069-45aa-b826-e3dcf2cd684c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQ5NTYsIm5iZiI6MTcwMDkyNDY1NiwicGF0aCI6Ii8yMzQxMjg5OS8yODU1NjQ3NTMtZmI2ZDk5MDMtYTA2OS00NWFhLWI4MjYtZTNkY2YyY2Q2ODRjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDE1MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MjVjYTFhMThjZDliOTEzN2QxMmE3MWEyYTU1Y2NjNGY4MmYzNDI2NzhhMmZhYmNiNzE1YTIzYTg3MmUzNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3mzt4H3cLjtGZAfCc7QfUgzQ0vceJUKbUbRY9HQbn4)
> 
> So all it does is open a side pane for the word at the caret.

Great!
Mine does not work in Emacs and Doom, because it hangs over an infinite loop when I hit Enter on Strong numbers, because something related to my fonts configuration:

*message* buffer:

Invalid face attribute :height nil [163 times]
QuitInvalid face attribute :height nil
Invalid face attribute :height nil [47 times]

:(

**Comment by Zacalot** [comment]
I don't use Doom, so not sure what the root of that error is, so I just made a new push to add a customizable option for disabling the :height attribute, so after updating you can try disabling it with M-x customize or this:
`(setq bible-mode-superscript-enabled nil)`

**Comment by OrionRandD** [comment]
> I don't use Doom, so not sure what the root of that error is, so I just made a new push to add a customizable option for disabling the :height attribute, so after updating you can try disabling it with M-x customize or this: `(setq bible-mode-superscript-enabled nil)`

Still hangs in Doom and Emacs-normal Estate...
Invalid face attribute :height nil [65 times]
QuitInvalid face attribute :height nil
Invalid face attribute :height nil [19 times]
:(
The package is wonderful. But, I was attracted by it, just because the possibility of Strong's numbers word analyses...
Unfortunately not working here...

**Comment by Zacalot** [comment]
I pushed another update to ensure :height is never set to nil, but this shouldn't fix anything if your package was updated and `bible-mode-superscript-enabled` was set to `nil`. So it may be good to ensure your local package updated by checking if the `bible-mode-superscript-enabled `variable exists with `C-h v`. If it's not there, perhaps try reinstalling the package, or open the bible-mode.el file from this repository and run `M-x eval-buffer` to directly load it.

You could also check if this package works on a clean emacs by adding `-q` to your emacs startup commandline so that it doesn't load your config, then open the bible-mode.el file from this repository and run it with `M-x eval-buffer` before running `M-x bible-open`

Otherwise, if your package is certainly up to date, configured properly with `(setq bible-mode-superscript-enabled nil)`, and working on a clean `-q` emacs, I'd just recommend you try troubleshooting by disabling other packages in your config or checking if any other configuration settings can be changed in Doom, though I'm not familiar with that environment so not sure what you could look at, probably anything related to fonts would be a good start.
